### PR TITLE
Remove react-native peerDependency

### PR DESCRIPTION
**Pull request by dsernst**
Fixes https://github.com/nandorojo/swr-firestore/issues/30

### CODE REVIEW

**Comment by dsernst** [comment]
Can you push this to npm? 🙂

**Comment by nandorojo** [comment]
Yeah thanks for your patience on this. Pushing out a few updates shortly once I finish a big project this week

**Comment by dsernst** [comment]
Fun 👍

**Comment by nandorojo** [comment]
Published in `v0.10.2`

**Pull request merged**
